# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yons/projects/stereocamera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yons/projects/stereocamera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yons/projects/stereocamera/CMakeFiles /home/yons/projects/stereocamera/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yons/projects/stereocamera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stereo_camera

# Build rule for target.
stereo_camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereo_camera
.PHONY : stereo_camera

# fast build rule for target.
stereo_camera/fast:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/build
.PHONY : stereo_camera/fast

src/adjustimg.o: src/adjustimg.cpp.o

.PHONY : src/adjustimg.o

# target to build an object file
src/adjustimg.cpp.o:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/adjustimg.cpp.o
.PHONY : src/adjustimg.cpp.o

src/adjustimg.i: src/adjustimg.cpp.i

.PHONY : src/adjustimg.i

# target to preprocess a source file
src/adjustimg.cpp.i:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/adjustimg.cpp.i
.PHONY : src/adjustimg.cpp.i

src/adjustimg.s: src/adjustimg.cpp.s

.PHONY : src/adjustimg.s

# target to generate assembly for a file
src/adjustimg.cpp.s:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/adjustimg.cpp.s
.PHONY : src/adjustimg.cpp.s

src/calibration.o: src/calibration.cpp.o

.PHONY : src/calibration.o

# target to build an object file
src/calibration.cpp.o:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/calibration.cpp.o
.PHONY : src/calibration.cpp.o

src/calibration.i: src/calibration.cpp.i

.PHONY : src/calibration.i

# target to preprocess a source file
src/calibration.cpp.i:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/calibration.cpp.i
.PHONY : src/calibration.cpp.i

src/calibration.s: src/calibration.cpp.s

.PHONY : src/calibration.s

# target to generate assembly for a file
src/calibration.cpp.s:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/calibration.cpp.s
.PHONY : src/calibration.cpp.s

src/feature_extract.o: src/feature_extract.cpp.o

.PHONY : src/feature_extract.o

# target to build an object file
src/feature_extract.cpp.o:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/feature_extract.cpp.o
.PHONY : src/feature_extract.cpp.o

src/feature_extract.i: src/feature_extract.cpp.i

.PHONY : src/feature_extract.i

# target to preprocess a source file
src/feature_extract.cpp.i:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/feature_extract.cpp.i
.PHONY : src/feature_extract.cpp.i

src/feature_extract.s: src/feature_extract.cpp.s

.PHONY : src/feature_extract.s

# target to generate assembly for a file
src/feature_extract.cpp.s:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/feature_extract.cpp.s
.PHONY : src/feature_extract.cpp.s

src/get_depth.o: src/get_depth.cpp.o

.PHONY : src/get_depth.o

# target to build an object file
src/get_depth.cpp.o:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/get_depth.cpp.o
.PHONY : src/get_depth.cpp.o

src/get_depth.i: src/get_depth.cpp.i

.PHONY : src/get_depth.i

# target to preprocess a source file
src/get_depth.cpp.i:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/get_depth.cpp.i
.PHONY : src/get_depth.cpp.i

src/get_depth.s: src/get_depth.cpp.s

.PHONY : src/get_depth.s

# target to generate assembly for a file
src/get_depth.cpp.s:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/get_depth.cpp.s
.PHONY : src/get_depth.cpp.s

src/image_stitch.o: src/image_stitch.cpp.o

.PHONY : src/image_stitch.o

# target to build an object file
src/image_stitch.cpp.o:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/image_stitch.cpp.o
.PHONY : src/image_stitch.cpp.o

src/image_stitch.i: src/image_stitch.cpp.i

.PHONY : src/image_stitch.i

# target to preprocess a source file
src/image_stitch.cpp.i:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/image_stitch.cpp.i
.PHONY : src/image_stitch.cpp.i

src/image_stitch.s: src/image_stitch.cpp.s

.PHONY : src/image_stitch.s

# target to generate assembly for a file
src/image_stitch.cpp.s:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/image_stitch.cpp.s
.PHONY : src/image_stitch.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/stereo_camera.dir/build.make CMakeFiles/stereo_camera.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... stereo_camera"
	@echo "... edit_cache"
	@echo "... src/adjustimg.o"
	@echo "... src/adjustimg.i"
	@echo "... src/adjustimg.s"
	@echo "... src/calibration.o"
	@echo "... src/calibration.i"
	@echo "... src/calibration.s"
	@echo "... src/feature_extract.o"
	@echo "... src/feature_extract.i"
	@echo "... src/feature_extract.s"
	@echo "... src/get_depth.o"
	@echo "... src/get_depth.i"
	@echo "... src/get_depth.s"
	@echo "... src/image_stitch.o"
	@echo "... src/image_stitch.i"
	@echo "... src/image_stitch.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

